# Generated by Django 5.1.6 on 2025-02-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='_url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
