# Generated by Django 5.1.6 on 2025-02-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_publisher', '0002_article__url_article_url_alter_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='court',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
